# This is a basic workflow to help you get started with Actions

name: code quality
 
# Controls when the action will run. 
on: [ pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '7.3'
          
      # Run composer install
      - name: Composer install dev repositories
        run: composer install --dev
        
      # Run php code sniffer
      - name: Run php code sniffer
        run: make phpcs

      # Run phpstan
      - name: Run phpstan
        run: make phpstan
